language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-19.1.0
    - android-19
    - extra-android-support
    - extra-android-m2repository

script: ./gradlew :piwik_sdk:test

after_success: ./gradlew :piwik_sdk:jacocoTestReport coveralls
